
t :
	./exemple-taux-cpu

MAX := 180000000

t1 :
	./exemple-taux-cpu $(MAX)

t5 :
	./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX)

t10 :
	./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX) & ./exemple-taux-cpu $(MAX)

